/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import static Tela.Split.getFileChooser;
import static Tela.Split.setLastDir;
import static Tela.Split.splitPdfFile;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfDocument;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.PdfStamper;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;

/**
 *
 * @author alexnantua
 */
public class Split_PDF_Viewer extends javax.swing.JFrame {

    /**
     * Creates new form PDF_Viewer
     */
    public Split_PDF_Viewer() {
        initComponents();
        setLocationRelativeTo(null);
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        split = new javax.swing.JButton();
        saida_Text = new javax.swing.JTextField();
        Procurar_Saida = new javax.swing.JButton();
        pdf1 = new javax.swing.JLabel();
        pdf1_Text = new javax.swing.JTextField();
        Procurar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PagInicial_1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PagFinal_1 = new javax.swing.JTextField();
        saida = new javax.swing.JLabel();
        PagInicial_2 = new javax.swing.JTextField();
        PagFinal_2 = new javax.swing.JTextField();
        VER = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PDF EDITOR - V.1.0 - By. Alexandre Nântua");

        split.setText("MANTER PÁGINAS SELECIONADAS");
        split.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splitActionPerformed(evt);
            }
        });

        Procurar_Saida.setText("PROCURAR");
        Procurar_Saida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Procurar_SaidaActionPerformed(evt);
            }
        });

        pdf1.setText("PDF");

        Procurar1.setText("PROCURAR");
        Procurar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Procurar1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Intervalo - Página Inicial:");

        jLabel2.setText("Intervalo - Página Final:");

        PagFinal_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PagFinal_1FocusLost(evt);
            }
        });

        saida.setText("SAÍDA");

        PagInicial_2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PagInicial_2FocusLost(evt);
            }
        });

        VER.setText("VER");
        VER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VERActionPerformed(evt);
            }
        });

        jButton1.setText("LIMPAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PagInicial_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PagInicial_2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PagFinal_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PagFinal_2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(split)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(pdf1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pdf1_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Procurar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VER))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saida_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Procurar_Saida)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pdf1)
                    .addComponent(pdf1_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Procurar1)
                    .addComponent(VER))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saida)
                    .addComponent(saida_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Procurar_Saida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(PagInicial_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(PagFinal_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(split)
                        .addComponent(PagInicial_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PagFinal_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void splitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_splitActionPerformed
        String user = System.getProperty("user.name");
        String nameFile = "-split.pdf";
        OutputStream output = null;
        String saidaEmpty = "C:/Users/" + user + "/Documents/" + nameFile;
        String pagesToKeep_Inicial = null;
        String pagesToKeep_Final = null;
        Integer pi1 = null;
        Integer pi2 = null;
        Integer pf1 = null;
        Integer pf2 = null;

        //PagInicial_1.set
        if (PagInicial_2.getText().isEmpty()) {
            pi2 = null;
        } else {
            pi2 = Integer.valueOf(PagInicial_2.getText());
        }
        if (PagFinal_1.getText().isEmpty()) {
            pf1 = null;
        } else {
            pf1 = Integer.valueOf(PagFinal_1.getText());
        }

        //condições
        if (pdf1_Text.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum arquivo adicionado.");
        } else {

            if (PagInicial_1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Página inicial não inserida.");
            } else {

                if (PagFinal_2.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Página final não inserida.");
                } else {

                    if (!PagFinal_1.getText().isEmpty()) {
                        if (Integer.parseInt(PagFinal_2.getText()) < Integer.parseInt(PagFinal_1.getText())) {
                            JOptionPane.showMessageDialog(null, "Verifique o intervalo selecionado.");
                            PagFinal_2.setText("");
                            PagFinal_2.requestFocus();
                        }
                    }

                    try {
                        PdfReader reader = new PdfReader(pdf1_Text.getText());

                        if (pdf1_Text.getText().isEmpty()) {
                            JOptionPane.showMessageDialog(null, "Nenhum arquivo foi selecionado.");
                        } else {
                            if (saida_Text.getText().isEmpty()) {
                                saida_Text.setText(saidaEmpty);
                            } else {
                                saida_Text.setText(saida_Text.getText() + nameFile);
                            }
                        }

                        if (PagInicial_2.getText().isEmpty() || PagFinal_1.getText().isEmpty()) {
                            pagesToKeep_Inicial = PagInicial_1.getText();
                            pagesToKeep_Final = PagFinal_2.getText();

                            reader.selectPages(pagesToKeep_Inicial + "-" + pagesToKeep_Final);
                            reader.removeUnusedObjects();

                            PdfStamper stamper = new PdfStamper(reader, new FileOutputStream(saida_Text.getText()));
                            stamper.close();

                            openpdf(saida_Text.getText());
                        } else {
                            pagesToKeep_Inicial = Integer.parseInt(PagInicial_1.getText())
                                    + "-" + Integer.parseInt(PagInicial_2.getText());
                            pagesToKeep_Final = Integer.parseInt(PagFinal_1.getText())
                                    + "-" + Integer.parseInt(PagFinal_2.getText());
                            reader.selectPages(pagesToKeep_Inicial + "," + pagesToKeep_Final);
                            reader.removeUnusedObjects();

                            PdfStamper stamper = new PdfStamper(reader, new FileOutputStream(saida_Text.getText()));
                            stamper.close();

                            openpdf(saida_Text.getText());
                        }

//                        splitPdfFile(new FileInputStream(pdf1_Text.getText()), new FileOutputStream(saida_Text.getText()), Integer.parseInt(PagInicial.getText()), Integer.parseInt(PagFinal.getText()));
                        JOptionPane.showMessageDialog(null, "PDF gerado com sucesso em " + saida_Text.getText());

                    } catch (FileNotFoundException ex) {
                        JOptionPane.showMessageDialog(null, ex);
                    } catch (DocumentException | HeadlessException | IOException | NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_splitActionPerformed

    private void Procurar_SaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Procurar_SaidaActionPerformed
        JFileChooser fc = getFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            setLastDir(fc.getSelectedFile());
            File arquivo = fc.getSelectedFile();
            saida_Text.setText(arquivo.getPath());

        } else {
            saida_Text.setText("");
        }
    }//GEN-LAST:event_Procurar_SaidaActionPerformed

    private void Procurar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Procurar1ActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PDF", "pdf");
        JFileChooser fc = getFileChooser();
        fc.setFileFilter(filter);
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            setLastDir(fc.getSelectedFile());
            File arquivo = fc.getSelectedFile();
            pdf1_Text.setText(arquivo.getPath());
            openpdf(pdf1_Text.getText());

        } else {
            pdf1_Text.setText("");
        }
    }//GEN-LAST:event_Procurar1ActionPerformed

    private void VERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VERActionPerformed
        openpdf(pdf1_Text.getText());
    }//GEN-LAST:event_VERActionPerformed

    private void PagInicial_2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PagInicial_2FocusLost
        if (!PagInicial_1.getText().isEmpty()) {
            if (Integer.parseInt(PagInicial_1.getText()) > Integer.parseInt(PagInicial_2.getText())) {
                JOptionPane.showMessageDialog(null, "Verifique o intervalo selecionado.");
                PagInicial_2.setText("");
                PagInicial_2.requestFocus();
            }
        } else if (PagInicial_1.getText().isEmpty() && !PagInicial_2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Primeiro campo de intervalo sem dados.");
        }
    }//GEN-LAST:event_PagInicial_2FocusLost

    private void PagFinal_1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PagFinal_1FocusLost
        if (!PagInicial_2.getText().isEmpty()) {
            if (Integer.parseInt(PagFinal_1.getText()) < Integer.parseInt(PagInicial_2.getText())
                    || !PagInicial_1.getText().isEmpty() && PagInicial_2.getText().isEmpty()
                    || PagInicial_1.getText().isEmpty() && !PagInicial_2.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Verifique o intervalo selecionado.");
                PagFinal_1.setText("");
                PagFinal_1.requestFocus();
            }
        } else if (PagInicial_1.getText().isEmpty() && PagInicial_2.getText().isEmpty() && !PagFinal_1.getText().isEmpty()
                || !PagInicial_1.getText().isEmpty() && PagInicial_2.getText().isEmpty()
                || PagInicial_1.getText().isEmpty() && !PagInicial_2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha os campos anteriores.");
            PagFinal_1.setText("");
        }
    }//GEN-LAST:event_PagFinal_1FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pdf1_Text.setText("");
        saida_Text.setText("");
        PagInicial_1.setText("");
        PagInicial_2.setText("");
        PagFinal_1.setText("");
        PagFinal_2.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Split_PDF_Viewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Split_PDF_Viewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Split_PDF_Viewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Split_PDF_Viewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Split_PDF_Viewer().setVisible(true);
            }
        });
    }

    void openpdf(String file) {

        SwingController control = new SwingController();
        SwingViewBuilder factry = new SwingViewBuilder(control);
        JPanel veiwerCompntpnl = factry.buildViewerPanel();
        ComponentKeyBinding.install(control, veiwerCompntpnl);
        control.getDocumentViewController().setAnnotationCallback(
                new org.icepdf.ri.common.MyAnnotationCallback(
                        control.getDocumentViewController()));

        control.openDocument(file);
        jScrollPane1.setViewportView(veiwerCompntpnl);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PagFinal_1;
    private javax.swing.JTextField PagFinal_2;
    private javax.swing.JTextField PagInicial_1;
    private javax.swing.JTextField PagInicial_2;
    private javax.swing.JButton Procurar1;
    private javax.swing.JButton Procurar_Saida;
    public javax.swing.JButton VER;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pdf1;
    public javax.swing.JTextField pdf1_Text;
    private javax.swing.JLabel saida;
    private javax.swing.JTextField saida_Text;
    private javax.swing.JButton split;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("pdf.png")));
    }
}
